spring:
  application:
    name: exchange-service
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT:http://localhost:8888}
# Вся конфигурация вынесена в Config Server (exchange-service.yml)