server:
  port: ${APP_PORT:8080}
  tomcat:
    # На JDK >= 24 Tomcat APR по умолчанию отключён; при желании включи:
    use-apr: when-available

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:books}
    username: ${DB_USER:books}
    password: ${DB_PASSWORD:books}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    dev.petr.bookswap: INFO
    org.springframework.web: INFO
