server:
  port: ${APP_PORT:8080}

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:books}
    username: ${DB_USER:books}
    password: ${DB_PASSWORD:books}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    dev.petr.bookswap: INFO
    org.springframework.web: INFO
